MarketWeb/Areas/Admin/Controllers/AdminTinDangsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MarketWeb.Models;
using PagedList.Core;
using AspNetCoreHero.ToastNotification.Abstractions;
using MarketWeb.Helpper;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Authorization;
using System.Data;

namespace MarketWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "1")]
    public class AdminTinDangsController : Controller
    {
        private readonly dbMarketsContext _context;
        public INotyfService _notyfService { get; }
        public AdminTinDangsController(dbMarketsContext context, INotyfService notyfService)
        {
            _context = context;
            _notyfService = notyfService;
        }

        // GET: Admin/AdminTinDangs
        public IActionResult Index(int? page)
        {
            var ls = _context.TinDangs.AsNoTracking().ToList();
            foreach (var item in ls)
            {
                if (item.CreatedDate == null)
                {
                    item.CreatedDate = DateTime.Now;
                    _context.Update(item);
                    _context.SaveChanges();
                }
                    
            }

            var pageNumber = page == null || page <= 0 ? 1 : page.Value;
            var pageSize = 20;
            var IsTinDangs = _context.TinDangs
                .AsNoTracking()
                .OrderByDescending(x => x.PostId);
            PagedList<TinDang> models = new PagedList<TinDang>(IsTinDangs, pageNumber, pageSize);
            ViewBag.CurrentPage = pageNumber;
            return View(models);
        }

        // GET: Admin/AdminTinDangs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.TinDangs == null)
            {
                return NotFound();
            }

            var tinDang = await _context.TinDangs
                .FirstOrDefaultAsync(m => m.PostId == id);
            if (tinDang == null)
            {
                return NotFound();
            }

            return View(tinDang);
        }

        // GET: Admin/AdminTinDangs/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/AdminTinDangs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PostId,Title,Scontents,Contents,Thumb,Published,Alias,CreatedDate,Author,AccountId,Tags,CatId,IsHot,IsNewfeed,MetaKey,MetaDesc,Views")] TinDang tinDang, IFormFile fThumb)
        {
            if (ModelState.IsValid)
            {
                if (fThumb != null)
                {
                    string extension = Path.GetExtension(fThumb.FileName);
                    string imageName = Utilities.SEOUrl(tinDang.Title) + extension;
                    tinDang.Thumb = await Utilities.UploadFile(fThumb, @"tindang", imageName.ToLower());
                }
                if (string.IsNullOrEmpty(tinDang.Thumb)) tinDang.Thumb = "default.jpg";
                tinDang.Alias = Utilities.SEOUrl(tinDang.Title);
                tinDang.CreatedDate = DateTime.Now;
                _context.Add(tinDang);
                await _context.SaveChangesAsync();
                _notyfService.Success("Thêm thành công");
                return RedirectToAction(nameof(Index));
            }
            return View(tinDang);
        }

        // GET: Admin/AdminTinDangs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.TinDangs == null)
            {
                return NotFound();
            }

            var tinDang = await _context.TinDangs.FindAsync(id);
            if (tinDang == null)
            {
                return NotFound();
            }
            return View(tinDang);
        }

        // POST: Admin/AdminTinDangs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PostId,Title,Scontents,Contents,Thumb,Published,Alias,CreatedDate,Author,AccountId,Tags,CatId,IsHot,IsNewfeed,MetaKey,MetaDesc,Views")] TinDang tinDang, IFormFile fThumb)
        {
            if (id != tinDang.PostId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (fThumb != null)
                    {
                        string extension = Path.GetExtension(fThumb.FileName);
                        string imageName = Utilities.SEOUrl(tinDang.Title) + extension;
                        tinDang.Thumb = await Utilities.UploadFile(fThumb, @"tindang", imageName.ToLower());
                    }
                    if (string.IsNullOrEmpty(tinDang.Thumb)) tinDang.Thumb = "default.jpg";
                    tinDang.Alias = Utilities.SEOUrl(tinDang.Title);
                    _context.Update(tinDang);
                    await _context.SaveChangesAsync();
                    _notyfService.Success("Sửa thành công");
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TinDangExists(tinDang.PostId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tinDang);
        }

        // GET: Admin/AdminTinDangs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.TinDangs == null)
            {
                return NotFound();
            }

            var tinDang = await _context.TinDangs
                .FirstOrDefaultAsync(m => m.PostId == id);
            if (tinDang == null)
            {
                return NotFound();
            }

            return View(tinDang);
        }

        // POST: Admin/AdminTinDangs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.TinDangs == null)
            {
                return Problem("Entity set 'dbMarketsContext.TinDangs'  is null.");
            }
            var tinDang = await _context.TinDangs.FindAsync(id);
            if (tinDang != null)
            {
                _context.TinDangs.Remove(tinDang);
            }
            
            await _context.SaveChangesAsync();
            _notyfService.Success("Xoá thành công");
            return RedirectToAction(nameof(Index));
        }

        private bool TinDangExists(int id)
        {
          return (_context.TinDangs?.Any(e => e.PostId == id)).GetValueOrDefault();
        }
    }
}

MarketWeb/Areas/Admin/Views/AdminTinDangs/Create.cshtml
@model MarketWeb.Models.TinDang

@{
    ViewData["Title"] = "Thêm tin mới";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

@section Styles {
    <link href="~/adminassets/summernote/summernote.css" rel="stylesheet" />
    <link href="~/adminassets/summernote/summernote.min.css" rel="stylesheet" />
    <link href="~/adminassets/summernote/summernote-bs4.css" rel="stylesheet" />
    <link href="~/adminassets/summernote/summernote-bs4.min.css" rel="stylesheet" />
}

<form asp-controller="AdminTinDangs" asp-action="Create" method="post" enctype="multipart/form-data">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="page-header no-gutters has-tab">
        <div class="d-md-flex m-b-15 align-items-center justify-content-between">
            <div class="media align-items-center m-b-15">
            </div>
            <div class="m-b-15">
                <button class="btn btn-primary">
                    <i class="anticon anticon-save"></i>
                    <span>Save</span>
                </button>
            </div>
        </div>
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link active" data-toggle="tab" href="#product-edit-basic">Basic Info</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#product-edit-option">Option Info</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#product-edit-description">Description</a>
            </li>
        </ul>
    </div>
    <div class="tab-content m-t-15">
        <div class="tab-pane fade show active" id="product-edit-basic">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productName">Tên tiêu đề</label>
                        <input type="text" class="form-control" asp-for="Title">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productName">Mô tả ngắn</label>
                        <input type="text" class="form-control" asp-for="Scontents">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productBrand">Ảnh đại diện</label>
                        <input name="fThumb" type="file" class="form-control-file" asp-for="Thumb">
                        <span asp-validation-for="Thumb" class="text-danger"></span>
                    </div>
                    <div class="form-group d-flex align-items-center">
                        <div class="switch m-r-10">
                            <input type="checkbox" asp-for="Published" checked="">
                            <label for="Published"></label>
                        </div>
                        <label>Published</label>
                    </div>
                    <div class="form-group d-flex align-items-center">
                        <div class="switch m-r-10">
                            <input type="checkbox" asp-for="IsHot" checked="">
                            <label for="IsHot"></label>
                        </div>
                        <label>IsHot</label>
                    </div>
                    <div class="form-group d-flex align-items-center">
                        <div class="switch m-r-10">
                            <input type="checkbox" asp-for="IsNewfeed" checked="">
                            <label for="IsNewfeed"></label>
                        </div>
                        <label>IsNewfeed</label>
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productName">CatId</label>
                        <input type="text" class="form-control" asp-for="CatId">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productName">Views</label>
                        <input type="text" class="form-control" asp-for="Views">
                    </div>

                </div>
            </div>
        </div>
        <div class="tab-pane fade" id="product-edit-option">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productColors">MetaDesc</label>
                        <input type="text" class="form-control" asp-for="MetaDesc">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productFit">MetaKey</label>
                        <input type="text" class="form-control" asp-for="MetaKey">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productFit">Alias</label>
                        <input type="text" class="form-control" asp-for="Alias">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productFit">Author</label>
                        <input type="text" class="form-control" asp-for="Author">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productFit">AccountId</label>
                        <input type="text" class="form-control" asp-for="AccountId">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productFit">Tags</label>
                        <input type="text" class="form-control" asp-for="Tags">
                    </div>
                </div>
            </div>
        </div>
        <div class="tab-pane fade" id="product-edit-description">
            <div class="card">
                <div class="card-body">
                    <label class="font-weight-semibold" for="pageName">Contents</label>
                    <input type="text" class="summernote" asp-for="Contents">
                </div>

            </div>
        </div>
    </div>
</form>

@section Scripts {

    <script src="~/adminassets/vendors/select2/select2.min.js"></script>
    <script src="~/adminassets/js/pages/e-commerce-product-edit.js"></script>
    <script src="~/adminassets/summernote/summernote-bs4.js"></script>
    <script>
        jQuery(document).ready(function () {
            $('.summernote').summernote({
                fontNames: ['Arial', 'Arial Black', 'Comic Sans Ms'],
                styleTags: ['p', 'h1', 'h2', 'h3', 'h4', 'h5'],
                height: 200,
                minHeight: null,
                maxHeight: null,
                focus: true
            });

        });
    </script>

}

MarketWeb/Areas/Admin/Views/AdminTinDangs/Delete.cshtml
@model MarketWeb.Models.TinDang

@{
    ViewData["Title"] = "Xác nhận xoá tin" + Model.Title;
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <a class="breadcrumb-item" asp-area="Admin" asp-controller="AdminTinDangs" asp-action="Index">Danh sách tin</a>
            <span class="breadcrumb-item active">Xác nhận xoá trang : @Model.Title</span>
        </nav>
    </div>
</div>

<div class="card">
    <div class="card-body">
        <h4 class="card-title">Xác nhận xoá tin : @Model.Title</h4>
        <div class="table-responsive">
            <table class="product-info-table m-t-20">
                <tbody>
                    <tr>
                        <td>ID:</td>
                        <td class="text-dark font-weight-semibold">@Model.PostId</td>
                    </tr>
                    <tr>
                        <td>Tên tin:</td>
                        <td>@Model.Title</td>
                    </tr>
                    <tr>
                        <td>Nội dung:</td>
                        <td>@Model.Contents</td>
                    </tr>
                    <tr>
                        <td>Nội dung ngắn:</td>
                        <td>@Model.Scontents</td>
                    </tr>
                    <tr>
                        <td>Hình ảnh:</td>
                        <td>
                            <img width="200" height="200" src="~/images/tindang/@Model.Thumb" alt="@Model.Title" />
                        </td>
                    </tr>
                    <tr>
                        <td>Published:</td>
                        <td>
                            @if (Model.Published)
                            {
                                <div class="switch m-r-10">
                                    <input type="checkbox" id="switch-1" checked="">
                                    <label for="switch-1"></label>
                                </div>
                            }
                            else
                            {
                                <div class="switch m-r-10">
                                    <input type="checkbox" id="switch-2">
                                    <label for="switch-2"></label>
                                </div>
                            }
                        </td>
                        
                    </tr>
                    <tr>
                        <td>IsHot:</td>
                        <td>
                            @if (Model.IsHot)
                            {
                                <div class="switch m-r-10">
                                    <input type="checkbox" id="switch-1" checked="">
                                    <label for="switch-1"></label>
                                </div>
                            }
                            else
                            {
                                <div class="switch m-r-10">
                                    <input type="checkbox" id="switch-2">
                                    <label for="switch-2"></label>
                                </div>
                            }
                        </td>
                    </tr>
                    <tr>
                        <td>IsNewfeed:</td>
                        <td>
                            @if (Model.IsNewfeed)
                            {
                                    <div class="switch m-r-10">
                                        <input type="checkbox" id="switch-1" checked="">
                                        <label for="switch-1"></label>
                                    </div>
                            }
                            else
                            {
                                    <div class="switch m-r-10">
                                        <input type="checkbox" id="switch-2">
                                        <label for="switch-2"></label>
                                    </div>
                            }
                        </td>
                    </tr>
                    <tr>
                        <td>Ngày tạo:</td>
                        <td>@Model.CreatedDate</td>
                    </tr>

                    <tr>
                        <td>Tiêu đề:</td>
                        <td>@Model.Title</td>
                    </tr>
                    <tr>
                        <td>MetaKey:</td>
                        <td>@Model.MetaKey</td>
                    </tr>
                    <tr>
                        <td>MetaDesc:</td>
                        <td>@Model.MetaDesc</td>
                    </tr>
                    <tr>
                        <td>Alias:</td>
                        <td>@Model.Alias</td>
                    </tr>
                    <tr>
                        <td>Tags:</td>
                        <td>@Model.Tags</td>
                    </tr>
                    <tr>
                        <td>Author:</td>
                        <td>@Model.Author</td>
                    </tr>
                    <tr>
                        <td>AccountId:</td>
                        <td>@Model.AccountId</td>
                    </tr>
                    <tr>
                        <td>Xác nhận xoá:</td>
                        <td>
                            <form asp-controller="AdminTinDangs" asp-action="Delete" asp-route-id="@Model.PostId">
                                <input type="hidden" asp-for="PostId" />
                                <input type="submit" value="Xác nhận xoá" class="btn btn-danger" />
                            </form>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

MarketWeb/Areas/Admin/Views/AdminTinDangs/Details.cshtml
@model MarketWeb.Models.TinDang

@{
    ViewData["Title"] = "Thông tin tin tức" + Model.Title;
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <a class="breadcrumb-item" asp-area="Admin" asp-controller="AdminTinDangs" asp-action="Index">Danh sách tin</a>
            <span class="breadcrumb-item active">Thông tin tin tức : @Model.Title</span>
        </nav>
    </div>
</div>

<div class="card">
    <div class="card-body">
        <h4 class="card-title">Thông tin tin tức : @Model.Title</h4>
        <div class="table-responsive">
            <table class="product-info-table m-t-20">
                <tbody>
                    <tr>
                        <td>ID:</td>
                        <td class="text-dark font-weight-semibold">@Model.PostId</td>
                    </tr>
                    <tr>
                        <td>Tiêu đề:</td>
                        <td>@Model.Title</td>
                    </tr>
                    <tr>
                        <td>Nội dung ngắn:</td>
                        <td>@Model.Scontents</td>
                    </tr>
                    <tr>
                        <td>Nội dung:</td>
                        <td>@Model.Contents</td>
                    </tr>
                    <tr>
                        <td>Hình ảnh:</td>
                        <td>
                            <img width="200" height="200" src="~/images/tindang/@Model.Thumb" alt="@Model.Title" />
                        </td>
                    </tr>
                    <tr>
                        <td>Published:</td>
                        <td>
                            @if (Model.Published)
                            {
                                <div class="switch m-r-10">
                                    <input type="checkbox" id="switch-1" checked="">
                                    <label for="switch-1"></label>
                                </div>
                            }
                            else
                            {
                                <div class="switch m-r-10">
                                    <input type="checkbox" id="switch-2">
                                    <label for="switch-2"></label>
                                </div>
                            }
                        </td>
                    </tr>
                    <tr>
                        <td>IsHot:</td>
                        <td>
                            @if (Model.IsHot)
                            {
                                <div class="switch m-r-10">
                                    <input type="checkbox" id="switch-1" checked="">
                                    <label for="switch-1"></label>
                                </div>
                            }
                            else
                            {
                                <div class="switch m-r-10">
                                    <input type="checkbox" id="switch-2">
                                    <label for="switch-2"></label>
                                </div>
                            }
                        </td>
                    </tr>
                    <tr>
                        <td>IsNewfeed:</td>
                        <td>
                            @if (Model.IsNewfeed)
                            {
                                <div class="switch m-r-10">
                                    <input type="checkbox" id="switch-1" checked="">
                                    <label for="switch-1"></label>
                                </div>
                            }
                            else
                            {
                                <div class="switch m-r-10">
                                    <input type="checkbox" id="switch-2">
                                    <label for="switch-2"></label>
                                </div>
                            }
                        </td>
                    </tr>
                    <tr>
                        <td>Ngày tạo:</td>
                        <td>@Model.CreatedDate</td>
                    </tr>

                    <tr>
                        <td>MetaKey:</td>
                        <td>@Model.MetaKey</td>
                    </tr>
                    <tr>
                        <td>MetaDesc:</td>
                        <td>@Model.MetaDesc</td>
                    </tr>
                    <tr>
                        <td>Alias:</td>
                        <td>@Model.Alias</td>
                    </tr>
                    <tr>
                        <td>Tags:</td>
                        <td>@Model.Tags</td>
                    </tr>
                    <tr>
                        <td>Author:</td>
                        <td>@Model.Author</td>
                    </tr>
                    <tr>
                        <td>AccountId:</td>
                        <td>@Model.AccountId</td>
                    </tr>
                    <tr>
                        <td>Views:</td>
                        <td>@Model.Views</td>
                    </tr>
                    
                </tbody>
            </table>
        </div>
    </div>
</div>

MarketWeb/Areas/Admin/Views/AdminTinDangs/Index.cshtml
@using PagedList.Core.Mvc
@model PagedList.Core.IPagedList<MarketWeb.Models.TinDang>

@{
    ViewData["Title"] = "Danh sách tin tức";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-header">

    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="AdminOrders" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <span class="breadcrumb-item active">Danh sách tin tức : page @ViewBag.CurrentPage</span>
        </nav>
    </div>
    
</div>
<div class="card">
    <div class="card-body">
        <div class="row m-b-30">
            <div class="col-lg-8">
                
            </div>
            <div class="col-lg-4 text-right">
                <a class="btn btn-primary" asp-controller="AdminTinDangs" asp-action="Create"> <i class="anticon anticon-plus-circle m-r-5"></i> <span>Add News</span></a>

            </div>
        </div>
        <div class="table-responsive">
            <table class="table table-hover e-commerce-table">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Tiêu đề</th>
                        <th>Ngày viết</th>
                        <th>IsHot</th>
                        <th>Trạng thái</th>
                        <th>#</th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model != null)
                    {
                        foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.PostId</td>
                                <td>@item.Title</td>
                                <td>@item.CreatedDate.Value.ToShortDateString()</td>
                                
                                <td>
                                    @if (item.IsHot == true)
                                    {
                                        <div class="d-flex align-items-center">
                                            <div class="badge badge-success badge-dot m-r-10"></div>
                                            <div>IsHot</div>
                                        </div>
                                    }
                                    else
                                    {
                                        <div class="d-flex align-items-center">
                                            <div class="badge badge-success badge-dot m-r-10"></div>
                                            <div>-</div>
                                        </div>
                                    }
                                </td>
                                <td>
                                    @if (item.Published == true)
                                    {
                                        <div class="d-flex align-items-center">
                                            <div class="badge badge-success badge-dot m-r-10"></div>
                                            <div>Public</div>
                                        </div>
                                    }
                                    else
                                    {
                                        <div class="d-flex align-items-center">
                                            <div class="badge badge-success badge-dot m-r-10"></div>
                                            <div>Non-Public</div>
                                        </div>
                                    }
                                </td>
                                <td>
                                    <a class="btn btn-primary btn-tone m-r-5" asp-area="Admin" asp-controller="AdminTinDangs" asp-action="Details" asp-route-id="@item.PostId">View</a>
                                    <a class="btn btn-secondary btn-tone m-r-5" asp-area="Admin" asp-controller="AdminTinDangs" asp-action="Edit" asp-route-id="@item.PostId">Edit</a>
                                    <a class="btn btn-success btn-tone m-r-5" asp-area="Admin" asp-controller="AdminTinDangs" asp-action="Delete" asp-route-id="@item.PostId">Delete</a>
                                </td>
                            </tr>
                        }
                    }


                </tbody>
            </table>
            <div aria-label="Page navigation example">
                <ul class="pagination">
                    <pager class="page-container" list="@Model" asp-area="Admin" asp-controller="AdminTinDangs" asp-action="Index" />
                </ul>
            </div>
        </div>
    </div>
</div>