MarketWeb/Areas/Admin/Controllers/AdminOrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MarketWeb.Models;
using AspNetCoreHero.ToastNotification.Abstractions;
using PagedList.Core;
using Microsoft.AspNetCore.Authorization;
using System.Data;

namespace MarketWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "1")]
    public class AdminOrdersController : Controller
    {
        private readonly dbMarketsContext _context;
        public INotyfService _notyfService { get; }

        public AdminOrdersController(dbMarketsContext context, INotyfService notyfService)
        {
            _context = context;
            _notyfService = notyfService;
        }

        // GET: Admin/AdminOrders
        public IActionResult Index(int? page)
        {
            var pageNumber = page == null || page <= 0 ? 1 : page.Value;
            var pageSize = 20;
            var IsOrders = _context.Orders.Include(o => o.Customer).Include(o => o.TransactStatus)
                .AsNoTracking()
                .OrderByDescending(x => x.OrderDate);
            PagedList<Order> models = new PagedList<Order>(IsOrders, pageNumber, pageSize);
            ViewBag.CurrentPage = pageNumber;
            return View(models);
        }

        // GET: Admin/AdminOrders/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Orders == null)
            {
                return NotFound();
            }

            var order = await _context.Orders
                .Include(o => o.Customer)
                .Include(o => o.TransactStatus)
                .FirstOrDefaultAsync(m => m.OrderId == id);
            if (order == null)
            {
                return NotFound();
            }

            var Chitietdonhang = _context.OrderDetails
                .AsNoTracking()
                .Include(x => x.Product)
                .Where(x => x.OrderId == order.OrderId)
                .OrderBy(x => x.OrderDetailId)
                .ToList();
            ViewBag.ChiTiet = Chitietdonhang;

            string phuongxa = GetNameLocation(order.Ward.Value);
            string quanhuyen = GetNameLocation(order.District.Value);
            string tinhthanh = GetNameLocation(order.LocationId.Value);
            var fullAddress = $"{order.Address}, {phuongxa}, {quanhuyen}, {tinhthanh}";
            ViewBag.fullAddress = fullAddress;
            return View(order);
        }

        public async Task<IActionResult> ChangeStatus(int? id)
        {
            if (id == null || _context.Orders == null)
            {
                return NotFound();
            }

            var order = await _context.Orders.FindAsync(id);
            if (order == null)
            {
                return NotFound();
            }
            ViewData["TrangThai"] = new SelectList(_context.TransactStatuses, "TransactStatusId", "Status", order.TransactStatusId);
            return PartialView("ChangeStatus", order);
        }

        [HttpPost]
        public async Task<IActionResult> ChangeStatus(int id, [Bind("OrderId,CustomerId,OrderDate,ShipDate,TransactStatusId,Deleted,Paid,PaymentDate,TotalMoney,PaymentId,Note,Address,LocationId,District,Ward")] Order order)
        {
            if (id != order.OrderId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var donhang = await _context.Orders
                        .AsNoTracking()
                        .Include(x => x.Customer)
                        .FirstOrDefaultAsync(x => x.OrderId == id);
                    if (donhang != null)
                    {
                        donhang.Paid = order.Paid;
                        donhang.Deleted = order.Deleted;
                        donhang.TransactStatusId = order.TransactStatusId;
                        if (donhang.Paid == true)
                        {
                            donhang.PaymentDate = DateTime.Now;
                        }
                        if (donhang.TransactStatusId == 5)
                            donhang.Deleted = true;
                        if (donhang.TransactStatusId == 3)
                            donhang.ShipDate = DateTime.Now;
                    }
                    _context.Update(donhang);
                    await _context.SaveChangesAsync();
                    _notyfService.Success("Cập nhật thành công");
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrderExists(order.OrderId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["TrangThai"] = new SelectList(_context.TransactStatuses, "TransactStatusId", "Status", order.TransactStatusId);
            return PartialView("ChangStatus", order);
        }

        public string GetNameLocation(int idlocation)
        {
            try
            {
                var location = _context.Locations
                    .AsNoTracking()
                    .SingleOrDefault(x => x.LocationId == idlocation);
                if (location != null)
                {
                    return location.NameWithType;
                }
            }
            catch
            {
                return string.Empty;
            }
            return string.Empty;
        }

        // GET: Admin/AdminOrders/Create
        public IActionResult Create()
        {
            ViewData["CustomerId"] = new SelectList(_context.Customers, "CustomerId", "CustomerId");
            ViewData["TransactStatusId"] = new SelectList(_context.TransactStatuses, "TransactStatusId", "TransactStatusId");
            return View();
        }

        // POST: Admin/AdminOrders/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("OrderId,CustomerId,OrderDate,ShipDate,TransactStatusId,Deleted,Paid,PaymentDate,TotalMoney,PaymentId,Note,Address,LocationId,District,Ward")] Order order)
        {
            if (ModelState.IsValid)
            {
                _context.Add(order);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CustomerId"] = new SelectList(_context.Customers, "CustomerId", "CustomerId", order.CustomerId);
            ViewData["TransactStatusId"] = new SelectList(_context.TransactStatuses, "TransactStatusId", "TransactStatusId", order.TransactStatusId);
            return View(order);
        }

        // GET: Admin/AdminOrders/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Orders == null)
            {
                return NotFound();
            }

            var order = await _context.Orders.FindAsync(id);
            if (order == null)
            {
                return NotFound();
            }
            ViewData["CustomerId"] = new SelectList(_context.Customers, "CustomerId", "CustomerId", order.CustomerId);
            ViewData["TransactStatusId"] = new SelectList(_context.TransactStatuses, "TransactStatusId", "TransactStatusId", order.TransactStatusId);
            return View(order);
        }

        // POST: Admin/AdminOrders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("OrderId,CustomerId,OrderDate,ShipDate,TransactStatusId,Deleted,Paid,PaymentDate,TotalMoney,PaymentId,Note,Address,LocationId,District,Ward")] Order order)
        {
            if (id != order.OrderId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(order);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrderExists(order.OrderId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CustomerId"] = new SelectList(_context.Customers, "CustomerId", "CustomerId", order.CustomerId);
            ViewData["TransactStatusId"] = new SelectList(_context.TransactStatuses, "TransactStatusId", "TransactStatusId", order.TransactStatusId);
            return View(order);
        }

        // GET: Admin/AdminOrders/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Orders == null)
            {
                return NotFound();
            }

            var order = await _context.Orders
                .Include(o => o.Customer)
                .Include(o => o.TransactStatus)
                .FirstOrDefaultAsync(m => m.OrderId == id);
            if (order == null)
            {
                return NotFound();
            }

            var Chitietdonhang = _context.OrderDetails
                .AsNoTracking()
                .Include(x => x.Product)

MarketWeb/Areas/Admin/Views/AdminOrders/ChangeStatus.cshtml
@model MarketWeb.Models.Order

<div class="modal-header">
    <h1 class="modal-title">Thông tin đơn hàng</h1>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>

<div class="modal-body">
    <div class="card">
        <div class="card-body">
            <h1 class="card-title">Thông tin đơn hàng # @Model.OrderId</h1>
            <div class="table-responsive">
                <table class="product-info-table m-t-20">
                    <tbody>
                        <tr>
                            <td>ID:</td>
                            <td class="text=dark font-weight-semibold">@Model.OrderId</td>
                        </tr>
                        <tr>
                            <td>Ngày mua hàng:</td>
                            <td>@Model.OrderDate</td>
                        </tr>
                        <tr>
                            <td>Khách hàng:</td>
                            <td>@Model.Customer.FullName</td>
                        </tr>
                        <tr>
                            <td>Số điện thoại:</td>
                            <td>@Model.Customer.Phone</td>
                        </tr>
                        <tr>
                            <td>Địa chỉ:</td>
                            <td>@Model.Customer.Address</td>
                        </tr>
                        <tr>
                            <td>Tổng tiền:</td>
                            <td>@Model.TotalMoney.ToString("#,##0") VND</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<div class="card">
    <div class="card-body">
        <form asp-area="Admin" asp-controller="AdminOrders" asp-action="ChangeStatus" asp-route-id="@Model.">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="OrderId" />

            <div class="row">
                <div class="col-lg-6">
                    <div class="form-group">
                        <label>Chọn trạng thái đơn hàng</label>
                        <select class="form-control" asp-for="TransactStatusId" asp-items="ViewBag.TrangThai">
                            <option value="0" disabled selected>Chọn trạng thái đơn hàng</option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label>Đã thanh toán</label>
                <input asp-for="Paid" type="checkbox" />
                <span asp-validation-for="Paid" class="text-danger"></span>                
            </div>
            <div class="form-group">
                <label>Đơn hàng bị huỷ</label>
                <input asp-for="Deleted" type="checkbox" />
                <span asp-validation-for="Deleted" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-success">Lưu thay đổi</button>
        </form>
    </div>
</div>

MarketWeb/Areas/Admin/Views/AdminOrders/Create.cshtml
@model MarketWeb.Models.Order

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Create</h1>

<h4>Order</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CustomerId" class="control-label"></label>
                <select asp-for="CustomerId" class ="form-control" asp-items="ViewBag.CustomerId"></select>
            </div>
            <div class="form-group">
                <label asp-for="OrderDate" class="control-label"></label>
                <input asp-for="OrderDate" class="form-control" />
                <span asp-validation-for="OrderDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShipDate" class="control-label"></label>
                <input asp-for="ShipDate" class="form-control" />
                <span asp-validation-for="ShipDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TransactStatusId" class="control-label"></label>
                <select asp-for="TransactStatusId" class ="form-control" asp-items="ViewBag.TransactStatusId"></select>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Deleted" /> @Html.DisplayNameFor(model => model.Deleted)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Paid" /> @Html.DisplayNameFor(model => model.Paid)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="PaymentDate" class="control-label"></label>
                <input asp-for="PaymentDate" class="form-control" />
                <span asp-validation-for="PaymentDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TotalMoney" class="control-label"></label>
                <input asp-for="TotalMoney" class="form-control" />
                <span asp-validation-for="TotalMoney" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PaymentId" class="control-label"></label>
                <input asp-for="PaymentId" class="form-control" />
                <span asp-validation-for="PaymentId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Note" class="control-label"></label>
                <input asp-for="Note" class="form-control" />
                <span asp-validation-for="Note" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LocationId" class="control-label"></label>
                <input asp-for="LocationId" class="form-control" />
                <span asp-validation-for="LocationId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="District" class="control-label"></label>
                <input asp-for="District" class="form-control" />
                <span asp-validation-for="District" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ward" class="control-label"></label>
                <input asp-for="Ward" class="form-control" />
                <span asp-validation-for="Ward" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

MarketWeb/Areas/Admin/Views/AdminOrders/Delete.cshtml
@model MarketWeb.Models.Order

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
    List<OrderDetail> orderDetails = ViewBag.ChiTiet;
}

<div class="page-header">
    <h2 class="header-title"></h2>
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="AdminOrders" asp-action="Home" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang chủ</a>
            <a class="breadcrumb-item" asp-area="Admin" asp-controller="AdminOrders" asp-action="Index">Danh sách đơn hàng</a>
            <span class="breadcrumb-item active">Chi tiết đơn hàng</span>
        </nav>
    </div>
</div>
<div class="container">
    <div class="card">
        <div class="card-body">
            <div id="invoice" class="p-h-30">
                <div class="row m-t-20 lh-2">
                    <div class="col-sm-6">
                        <h3 class="p-l-10 m-t-10">THÔNG TIN ĐƠN HÀNG:</h3>
                        <address class="p-l-10 m-t-10">
                            <span class="font-weight-semibold text-dark">Họ và Tên: @Model.Customer.FullName</span><br>
                            <span>Địa chỉ: @Model.Customer.Address</span><br>
                            <span>Số điện thoại: @Model.Customer.Phone</span>
                        </address>
                    </div>
                    <div class="col-sm-6">
                        <div class="m-t-80">
                            <div class="text-dark text-uppercase d-inline-block">
                                <span class="font-weight-semibold text-dark">Mã đơn hàng :</span>
                            </div>
                            <div class="float-right">#@Model.OrderId</div>
                        </div>
                        <div class="text-dark text-uppercase d-inline-block">
                            <span class="font-weight-semibold text-dark">Ngày đặt hàng :</span>
                        </div>
                        <div class="float-right">@Model.OrderDate</div>
                        <br />
                        <div class="text-dark text-uppercase d-inline-block">
                            <span class="font-weight-semibold text-dark">Ngày Ship hàng :</span>
                        </div>
                        <div class="float-right">@Model.ShipDate</div>
                        <br />
                        <div class="text-dark text-uppercase d-inline-block">
                            <span class="font-weight-semibold text-dark">Trạng thái đơn hàng :</span>
                        </div>
                        <div class="float-right">@Model.TransactStatus.Status</div>
                    </div>
                </div>
                <div class="m-t-20">
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>No.</th>
                                    <th>Items</th>
                                    <th>Quantity</th>
                                    <th>Price</th>
                                    <th>Total</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (orderDetails != null && orderDetails.Count() > 0)
                                {
                                    int i = 1;
                                    foreach (var item in orderDetails)
                                    {
                                        string url = $"/{item.Product.Alias}-{item.Product.ProductId}.html";
                                        <tr>
                                            <th>@i</th>
                                            <td><a target="_blank" href="@url">@item.Product.ProductName</a></td>
                                            <td>@item.Amount</td>
                                            <td>@item.Price.Value.ToString("#,##0") VNĐ</td>
                                            <td>@item.TotalMoney.Value.ToString("#,##0") VNĐ</td>
                                        </tr>
                                        i++;
                                    }
                                }


                            </tbody>
                        </table>
                    </div>
                    <div class="row m-t-30 lh-1-8">
                        <div class="col-sm-12">
                            <div class="float-right text-right">
                                <h3><span class="font-weight-semibold text-dark">Tổng tiền :</span>@orderDetails.Sum(x => x.TotalMoney).Value.ToString("#,##0") VNĐ</h3>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<form asp-action="Delete" asp-for-id="@Model.OrderId">
    <input type="hidden" asp-for="OrderId" />
    <input type="submit" value="Xác nhận xóa đơn hàng" class="btn btn-danger" />
</form>

MarketWeb/Areas/Admin/Views/AdminOrders/Details.cshtml
@model MarketWeb.Models.Order

@{
    ViewData["Title"] = "Chi tiết hoá đơn #" + Model.OrderId;
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
    List<OrderDetail> orderDetails = ViewBag.ChiTiet;
}

<div class="page-container">


    <!-- Content Wrapper START -->
    <div class="main-content">
        <div class="page-header">
            <h2 class="header-title">Invoice</h2>
            <div class="header-sub-title">
                <nav class="breadcrumb breadcrumb-dash">
                    <a href="#" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
                    <a class="breadcrumb-item" asp-area="Admin" asp-controller="AdminOrders" asp-action="Index">Danh sách đơn hàng</a>
                    <span class="breadcrumb-item active">Chi tiết hoá đơn</span>
                </nav>
            </div>
        </div>
        <div class="container">
            <div class="card">
                <div class="card-body">
                    <div id="invoice" class="p-h-30">
                        <div class="row m-t-20 lh-2">
                            <div class="col-sm-9">
                                <h3 class="p-l-10 m-t-10">Hoá đơn</h3>
                                <address class="p-l-10 m-t-10">
                                    <span>@Model.Customer.FullName</span><br>
                                    <span>@ViewBag.fullAddress</span><br>
                                    <abbr class="text-dark" title="Phone">Số điện thoại: </abbr>
                                    <span>@Model.Customer.Phone</span>
                                </address>
                            </div>
                            <div class="col-sm-3">
                                <div class="m-t-80">
                                    <div class="text-dark text-uppercase d-inline-block">
                                        <span class="font-weight-semibold text-dark">Thông tin hoá đơn </span>
                                    </div>
                                    <div class="float-right">#@Model.OrderId</div>
                                </div>
                                <div class="text-dark text-uppercase d-inline-block">
                                    <span class="font-weight-semibold text-dark">Ngày mua :</span>
                                </div>
                                <div class="float-right">@Model.OrderDate</div>

                                <div class="text-dark text-uppercase d-inline-block">
                                    <span class="font-weight-semibold text-dark">Ngày giao hàng :</span>
                                </div>
                                <div class="float-right">@Model.ShipDate</div>

                                <div class="text-dark text-uppercase d-inline-block">
                                    <span class="font-weight-semibold text-dark">Trạng thái: </span>
                                </div>
                                <div class="float-right">@Model.TransactStatus.Status</div>
                            </div>
                        </div>
                        <div class="m-t-20">
                            <div class="table-responsive">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th>No.</th>
                                            <th>Items</th>
                                            <th>Quantity</th>
                                            <th>Price</th>
                                            <th>Total</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @if (orderDetails != null && orderDetails.Count() < 0)
                                        {
                                            int i = 1;
                                            foreach (var item in orderDetails)
                                            {
                                                string url = $"/{item.Product.Alias}--{item.Product.ProductId}.html";
                                                <tr>
                                                    <th>1</th>
                                                    <td><a target="_blank" href="@url">@item.Product.ProductName</a></td>
                                                    <td>@item.Amount</td>
                                                    <td>@item.Price.Value.ToString("#,##0") VND</td>
                                                    <td>@item.TotalMoney.Value.ToString("#,##0") VND</td>
                                                </tr>
                                                i++;
                                            }
                                        }
                                    </tbody>
                                </table>
                            </div>
                            <div class="row m-t-30 lh-1-8">
                                <div class="col-sm-12">
                                    <div class="float-right text-right">
                                        <h3><span class="font-weight-semibold text-dark">Tổng tiền :</span>@Model.TotalMoney.ToString("#,##0") VND</h3>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
</div>

MarketWeb/Areas/Admin/Views/AdminOrders/Index.cshtml
@using PagedList.Core.Mvc
@model PagedList.Core.IPagedList<MarketWeb.Models.Order>

@{
    ViewData["Title"] = "Danh sách đơn hàng - Page : " + ViewBag.CurrentPage;
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-header">

    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="AdminOrders" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <span class="breadcrumb-item active">Danh sách đơn hàng : page @ViewBag.CurrentPage</span>
        </nav>
    </div>
</div>
<div class="card">
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-hover e-commerce-table">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>ĐƠN HÀNG</th>
                        <th>NGÀY MUA</th>
                        <th>TỔNG TIỀN</th>
                        <th>TRẠNG THÁI</th>
                        <th>#</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model != null)
                    {
                        foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.OrderId</td>
                                <td>@item.Customer.FullName</td>
                                <td>@item.OrderDate</td>
                                <td>@item.TotalMoney.ToString("#,##0") VND</td>
                                <td>@item.TransactStatus.Status</td>
                                <td>
                                    <a class="btn btn-primary btn-tone m-r-5" asp-area="Admin" asp-controller="AdminOrders" asp-action="Details" asp-route-id="@item.OrderId">View</a>
                                    <a class="btn btn-secondary btn-tone m-r-5" asp-area="Admin" asp-controller="AdminOrders" asp-action="Edit" asp-route-id="@item.OrderId">Edit</a>
                                    <a class="btn btn-success btn-tone m-r-5" asp-area="Admin" asp-controller="AdminOrders" asp-action="Delete" asp-route-id="@item.OrderId">Delete</a>
                                    <a class="btn btn-success btn-tone m-r-5" asp-area="Admin" asp-controller="AdminOrders" asp-action="Delete" asp-route-id="@item.OrderDetails">Status</a>

                                </td>
                            </tr>
                        }
                    }


                </tbody>
            </table>
            <div aria-label="Page navigation example">
                <ul class="pagination">
                    <pager class="page-container" list="@Model" asp-area="Admin" asp-controller="AdminOrders" asp-action="Index" />
                </ul>
            </div>
        </div>
    </div>
</div>